### ISSUE TITLE
[Feature Request] Enable Parsing Webhook Messages. 

### ISSUE THREAD

**Issue by jusplainmike** [markokajzer/discord-soundbot#78] opened 2020-04-22 01:51 UTC
I am trying to get your bot to react to messages posted by a webhook. I have a lot of sounds added through the bot like a soundboard. Me and my friends use them when we game being silly. I created a webpage that sends a message using webhooks to a hidden channel on our server but the bot will not activate from messages the webhook post. It works when I type the commands into the channel on my desktop client. I have tried changing !message.author.bot to remove the ! but still doesn't work.

**Comment by jusplainmike** [comment] 2020-04-24 00:50
I tried a few things in the script but even removing every condition for a valid message but starting with command prefix still doesn't activate a command when the webhook post the message.

**Comment by markokajzer** [comment] 2020-04-24 07:05
Hey, thanks for the info. That'll be helpful when I look into the issue.

Stupid question: Does the bot have access to that "secret channel" where you receive the webhooks?

**Comment by jusplainmike** [comment] 2020-04-24 11:15
Yes the bot has access but I believe it's a permissions issue. I can't set
permissions on a webhook user. So I believe the bot is looking for if a
user who posted has a certain level of permissions.

**Comment by markokajzer** [comment] 2020-05-10 18:38
I definitely need to investigate this a bit more to understand how webhooks and webhook messages work. Not sure why it would be a permission issue 🤔

**Comment by jusplainmike** [comment] 2020-05-10 19:03
I might get into this next weekend. I'll reply with what I find.

**Comment by ibito** [comment] 2020-06-05 03:19
But the bot should join where the user issuing the command (in this case a webhook... might be none maybe?) isn't it?

**Comment by markokajzer** [comment] 2020-07-12 21:49
I looked into this a little bit and now see that I was quite confused about what's going on. I think there are two things here:

1) The webhook message comes from a "bot" (the webhook). Messages by bots are generally ignored.
2) The bot works by checking the voice channel of the author of a message. When the webhook comes in, it's just a message. In this case, the "author" of the message (the webhook) was not in a voice channel, so of course nothing will happen. What should happen in this case? How should the bot know which channel to join? Should it always be the same channel? Then we need something like sending sounds to specific channels, but that comes with its own problems. Should it always look for a given user? Should it look for just any user at all?

Thinking about it, the problem is not really the parsing of the webhook, which is simply a message from the bot. I will close this issue for now as I do not see an issue around as is. If you have a clearer understanding of requirements, i.e. what you would like to happen, feel free to open another issue.

**Closed by markokajzer** 2020-07-12 21:49 UTC
